### ISSUE TITLE
curl_mime_init Symbol not found

### ISSUE THREAD

**Issue by zdavatz** [claui/homebrew-public#3]
@claui I have question for you:

Installing Curl with homebrew and then running my app with a Curl dependency creates a crash with this output:
```
Dyld Error Message:
  Symbol not found: _curl_mime_init
  Referenced from: /Applications/AmiKo.app/Contents/MacOS/AmiKo
  Expected in: /usr/lib/libcurl.4.dylib
```
Is curl not configured with mime support in homebrew? Or is this a completly different issue?

**Comment by claui** [comment]
@zdavatz The path to `/usr/lib` in the error message suggests that the app is specifically looking for the symbol in system curl, not brewed curl.

What’s the output of `brew config`?

**Comment by zdavatz** [comment]
```
ywesees-MacBook-Pro:~ ywesee$ brew config
HOMEBREW_VERSION: 3.0.0
ORIGIN: https://github.com/Homebrew/brew
HEAD: ebc7cc36a0e029d58fac8cebd1b5ff583b3fd95b
Last commit: 6 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 296d564807c0c62e5ff93af1e8d096c53f0e7468
Core tap last commit: 2 days ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.xoVE86EY8a/org.macosforge.xquartz:0
HOMEBREW_MAKE_JOBS: 2
Homebrew Ruby: 2.6.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/bin/ruby
CPU: dual-core 64-bit penryn
Clang: 8.0 build 800
Git: 2.17.0 => /usr/local/bin/git
Curl: 7.43.0 => /usr/bin/curl
macOS: 10.11.6-x86_64
CLT: 8.2.0.0.1.1480973914
Xcode: 8.2.1
XQuartz: 2.7.11 => /opt/X11
```

**Comment by claui** [comment]
Thanks @zdavatz!

The line where it says:

```
macOS: 10.11.6-x86_64
```

suggests that you’re on El Capitan.
It smells a bit like El Capitan possibly not meeting your app’s system requirements, and the app therefore expecting a system curl version to be present that only ships with newer macOS versions.

Does the app’s vendor mention whether it supports macOS 10.11?

**Comment by zdavatz** [comment]
This is the App: http://pillbox.oddb.org/AmiKo-0.1.268-Darwin.dmg (you need to download the DB first).

The App only starts crashing after you select "Google Sync" in the settings. Before it works very well. "Google Sync" uses Curl and MIME to connect to the Google Servers. So I thought, that I could upgrade Curl to make it work.

This is the source of the App: https://github.com/zdavatz/amiko_linux

Is there no configure option for Curl like "configure --with-mime"?

**Comment by claui** [comment]
Thanks for the additional info and the download link @zdavatz.

> Is there no configure option for Curl like "configure --with-mime"?

Out of the box, `curl_mime_init` has been part of brewed curl [since the function first appeared, which was in version 7.56.0](https://curl.se/libcurl/c/curl_mime_init.html).

To confirm that your brewed curl has `curl_mime_init`, run:

```
$ nm -j /usr/local/opt/curl/lib/libcurl.4.dylib | grep curl_mime
```

and it should print, among a dozen other symbols, `curl_mime_init`.

This means **your brewed curl is already fine.** The thing is: the app seems to link to system curl (the one in `/usr/lib`, which is under Apple’s control), and **ignores brewed curl** entirely.

Up until Mojave, macOS shipped with Apple-controlled libcurl versions ≤ 7.54.0:

```
$ strings /usr/lib/libcurl.4.dylib | grep -F libcurl/
libcurl/7.54.0
```

(El Capitan ships with an even older libcurl.)
Those versions are so outdated that `curl_mime_init` simply wasn’t a thing yet:

```
$ nm -j /usr/lib/libcurl.4.dylib | grep curl_mime_init    # no output
```

Only in Catalina did Apple’s libcurl become new enough ([7.64.1](https://curl.se/mail/lib-2019-11/0066.html)) to include `curl_mime_init`.

That means: **upgrading your system to Catalina or newer will probably fix the issue.**
(If you try upgrading, I recommend that you do a full backup just in case it breaks any apps.)

Does that help?

**Comment by claui** [comment]
Are you, by chance, building the macOS app bundle yourself?
Because if so, another solution would be to include `/usr/local/lib` in the dyld search path and rebuild the app.

But still: upgrading macOS is the preferable solution. It gives you much better security.

**Comment by zdavatz** [comment]
> Are you, by chance, building the macOS app bundle yourself?
> Because if so, another solution would be to include `/usr/local/lib` in the dyld search path and rebuild the app.
> 
> But still: upgrading macOS is the preferable solution. It gives you much better security.

Ok, thank you I will do this!

**Comment by claui** [comment]
Thank you @zdavatz for your generous support. It’s super helpful, and much appreciated!
